### ISSUE TITLE
파이어스토어에 데이터를 추가하고 수정하고 삭제하는 부분을 Thunk로 다루는게 더 좋을까요?

### ISSUE THREAD

**Issue by nggoong** [nggoong/chinese-vocabulary#1]
제가 구현한 로직은 파이어베이스에서 데이터를 가져오는 기능만 Thunk로 처리를 하였고,
추가, 수정, 삭제 기능은 Thunk를 사용하지 않고 구현하였습니다.
예를 들면 추가하기 버튼 클릭 이벤트에 addDoc()를 바로 사용하였습니다.
그리고 dispatch()로 데이터를 가져와서 화면에서 업데이트 된 데이터를 보여주고 있습니다.

추가, 수정, 삭제하는 기능을 Thunk로 다루는게 더 괜찮은 방법인지 궁금합니다.

**Comment by leedaeho1188** [comment]
추사, 수정, 삭제 기능을 한 이벤트에서만 사용을 한다면 thunk를 사용하지 않아도 크게 문제를 없습니다. 
추가, 수정, 삭제 기능을 여러 이벤트에서 사용하게 된다면 thunk를 사용해서 모듈화를 시키는 방법이 유지보수를하고 코드 중복을 줄이는데 효율적입니다. :)

**Comment by nggoong** [comment]
> 추사, 수정, 삭제 기능을 한 이벤트에서만 사용을 한다면 thunk를 사용하지 않아도 크게 문제를 없습니다. 추가, 수정, 삭제 기능을 여러 이벤트에서 사용하게 된다면 thunk를 사용해서 모듈화를 시키는 방법이 유지보수를하고 코드 중복을 줄이는데 효율적입니다. :)

감사합니다!! :)
